language: go

go:
  - 1.5
  - 1.6

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=journal.coverprofile ./journal
  - go test -coverprofile=repository.coverprofile ./repository
  - go test -coverprofile=store.coverprofile ./store
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci